# Generated by Django 6.0.7 on 2026-07-18 15:06

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.get_chat_attachment_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.get_chat_voice_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_voice',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.get_voice_note_path),
        ),
    ]
