# Generated by Django 6.0.7 on 2026-07-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_message_attachment_alter_message_voice_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
